[frontends]
one-fe1 ansible_host=192.168.50.11
one-fe2 ansible_host=192.168.50.12

[nodes]
one-node1 ansible_host=192.168.50.21
one-node2 ansible_host=192.168.50.22

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
