# Inventario Ansible — Lab OpenNebula HA
# Todos los hosts son VMs KVM corriendo en tu laptop host (192.168.50.0/24)

[frontends]
one-fe1  ansible_host=192.168.50.11
one-fe2  ansible_host=192.168.50.12

[nodes]
one-node1  ansible_host=192.168.50.21
one-node2  ansible_host=192.168.50.22

[all:vars]
# Usuario creado por cloud-init
ansible_user=ubuntu
# Llave SSH (la misma que inyectaste con Terraform)
ansible_ssh_private_key_file=~/.ssh/id_ed25519
# Deshabilitar verificación de host para entorno de lab
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ConnectTimeout=15'
# Python del sistema en Ubuntu 22.04
ansible_python_interpreter=/usr/bin/python3

# Variables compartidas del laboratorio
[frontends:vars]
one_vip=192.168.50.10
one_fe1_ip=192.168.50.11
one_fe2_ip=192.168.50.12

[all:vars]
nfs_server_ip={{ lookup('env', 'HOST_IP') | default('192.168.50.1', true) }}
one_nfs_export=/var/lib/one/datastores